-- `codex-cli` becomes a reserved built-in key in this release. Move any historical
-- API provider using that key into an application-recognized migration namespace.
-- `_codex_` is never generated by the normal provider slugger; base36 BIGINT ids
-- keep the replacement unique and within provider VARCHAR(20). Only the key changes.
UPDATE `pw_user_ai_config`
SET `provider` = CONCAT('_codex_', LOWER(CONV(`id`, 10, 36)))
WHERE `provider` = 'codex-cli'
  AND COALESCE(
        JSON_UNQUOTE(JSON_EXTRACT(
          IF(JSON_VALID(`config`), `config`, '{}'),
          '$.protocol'
        )),
        ''
      ) <> 'CODEX_APP_SERVER';
