ALTER TABLE `pw_tts_cache_meta`
  ADD COLUMN `owner_user_id` BIGINT NULL AFTER `id`,
  ADD COLUMN `file_size_bytes` BIGINT NOT NULL DEFAULT 0 AFTER `relative_path`,
  ADD KEY `idx_pw_tts_cache_meta_owner` (`owner_user_id`),
  ADD CONSTRAINT `fk_pw_tts_cache_meta_owner`
    FOREIGN KEY (`owner_user_id`) REFERENCES `pw_user` (`id`) ON DELETE SET NULL;

INSERT INTO `pw_system_config`
(`group_name`, `config_key`, `value`, `value_type`, `description`) VALUES
('tts', 'tts.cache.max-entries', '5000', 'LONG',
 'Maximum global TTS cache entries; changes take effect within 60 seconds'),
('tts', 'tts.cache.max-bytes', '1073741824', 'LONG',
 'Maximum global TTS cache bytes; changes take effect within 60 seconds'),
('tts', 'tts.cache.max-entries-per-user', '500', 'LONG',
 'Maximum TTS cache entries generated by one user; changes take effect within 60 seconds'),
('tts', 'tts.cache.max-bytes-per-user', '104857600', 'LONG',
 'Maximum TTS cache bytes generated by one user; changes take effect within 60 seconds')
ON DUPLICATE KEY UPDATE
  `group_name` = VALUES(`group_name`),
  `value_type` = VALUES(`value_type`),
  `description` = VALUES(`description`);
